version: '3.8'

services:
  # Web应用服务
  web:
    build: .
    container_name: xinghan-web
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./assets:/var/www/html/assets
    restart: unless-stopped
